#!/bin/sh

# file: mkkb.sh
# project: wikidata2
# author: Pavel Raur (xraurp00@stud.fit.vutbr.cz)
# description: merges separate type files into KB

project_folder="$(readlink -f $0 | xargs -I{} dirname {})"
artist_file="$project_folder"/output/artists_merged.tsv
event_file="$project_folder"/output/events_merged.tsv
organization_file="$project_folder"/output/organizations_merged.tsv

output_file="$project_folder"/output/KB.tsv

if [ "$1" = "--help" ]; then
	echo 'Description:'
	echo 'Merges files generated by merging wikidata and wikipedia'
	echo 'into single KB.'
	exit 0
fi

echo 'Merging output files into KB'

echo "VERSION=cs_wd+wd_$(date '+%Y%m%d_%H%M%S')" > "$output_file"
cat "$project_folder"/HEAD "$artist_file" "$event_file" "$organization_file" \
>> "$output_file"

