#!/bin/sh

# file: mkkb.sh
# project: wikidata2
# author: Pavel Raur (xraurp00@stud.fit.vutbr.cz)
# description: merges separate type files into KB

project_folder="$(readlink -f $0 | xargs -I{} dirname {})"
output_dirname="output"

# unknown args
unknown=''

echo "Script \"${0}\" called with params: ${@}"

# get value of argument given as -avalue
get_simple_arg_value() {
	echo "$(echo "$1" | sed 's/^..\(.*\)/\1/')"
}

# get value of argument given as --arg=value
get_arg_value() {
	echo "$(echo "$1" | awk -F'=' '{ print $2 }')"
}

get_output_path() {
	echo "${project_folder}/${output_dirname}/${dump_name}/${lang}/${1}"
}

help() {
	echo "Usage:"
	echo "  sh mkkb.sh [args]"
	echo "Args:"
	echo "  --person       | -p  Person KB file."
	echo "  --group        | -g  Group KB file."
	echo "  --artist       | -a  Artist KB file."
	echo "  --geographical | -l  Geographical KB file."
	echo "  --event        | -e  Event KB file."
	echo "  --organization | -o  Organization KB file."
	echo "  --lang               Language of KB."
	echo "  --dump               Dump version."

	echo "Description:"
	echo "  Merges files generated by KB extraction into single KB file."
	exit 0
}

# parse args
while true; do
	case "$1" in
		--person|-p )
			person_file="$2"
			if [ -z "$2" ]; then
				echo 'Person file not specified!' >&2
				exit 1
			fi
			shift 2
			;;
		--person=* )
			person_file="$(get_arg_value "$1")"
			shift
			;;
		-p* )
			person_file="$(get_simple_arg_value "$1")"
			shift
			;;
		--group|-g )
			group_file="$2"
			if [ -z "$2" ]; then
				echo 'Group file not specified!' >&2
				exit 1
			fi
			shift 2
			;;
		--group=* )
			group_file="$(get_arg_value "$1")"
			shift
			;;
		-g* )
			group_file="$(get_simple_arg_value "$1")"
			shift
			;;
		--artist|-a )
			artist_file="$2"
			if [ -z "$2" ]; then
				echo 'Artist file not specified!' >&2
				exit 1
			fi
			shift 2
			;;
		--artist=* )
			artist_file="$(get_arg_value "$1")"
			shift
			;;
		-a* )
			artist_file="$(get_simple_arg_value "$1")"
			shift
			;;
		--geographical|-l )
			geographical_file="$2"
			if [ -z "$2" ]; then
				echo 'Geographical file no specified!' >&2
				exit 1
			fi
			shift 2
			;;
		--geographical=* )
			geographical_file="$(get_arg_value "$1")"
			shift
			;;
		-l* )
			geographical_file="$(get_simple_arg_value "$1")"
			shift
			;;
		--event|-e )
			event_file="$2"
			if [ -z "$2" ]; then
				echo 'Event file not specified!' >&2
				exit 1
			fi
			shift 2
			;;
		--event=* )
			event_file="$(get_arg_value "$1")"
			shift
			;;
		-e* )
			event_file="$(get_simple_arg_value "$1")"
			shift
			;;
		--organization|-o )
			organization_file="$2"
			if [ -z "$2" ]; then
				echo 'Organization file not specified!' >&2
				exit 1
			fi
			shift 2
			;;
		--organization=* )
			organization_file="$(get_arg_value "$1")"
			shift
			;;
		-o* )
			organization_file="$(get_simple_arg_value "$1")"
			shift
			;;
		--lang=* )
			lang="$(get_arg_value "$1")"
			shift
			;;
		--dump=* )
			dump_name=$(get_arg_value "${1}")
			dump_version=`echo "${dump_name}" | sed 's/wikidata-\([0-9]\{8\}\)-.*.json/\1/'`
			shift
			;;
		--help|-h )
			help
			shift
			;;
		* )
			unknown="$1"
			break
			;;
	esac
done

if [ -n "$unknown" ]; then
	echo "Unknown argument $unknown"'!' >&2
	exit 1
fi

output_file=$(get_output_path "KB.tsv")

person_file=${person_file:=`get_output_path "persons_unmerged.tsv"`}
group_file=${group_file:=`get_output_path "groups_wikidata2.tsv"`}
artist_file=${artist_file:=`get_output_path "artists_merged.tsv"`}
geographical_file=${geographical_file:=`get_output_path "geographical_wikidata2.tsv"`}
event_file=${event_file:=`get_output_path "events_merged.tsv"`}
organization_file=${organization_file:=`get_output_path "organizations_merged.tsv"`}

output_dir=`dirname "${output_file}"`

# setup - create output folder
[ -d "${output_dir}" ] || mkdir -p "${output_dir}"

echo 'Merging output files into KB'

echo "VERSION=${lang}_wd_${dump_version}_$(date '+%Y%m%d_%H%M%S')" > "$output_file"
cat "$project_folder"/HEAD "$person_file" "$group_file" "$artist_file" "$geographical_file" "$event_file" "$organization_file" \
>> "$output_file"

